### ISSUE TITLE
 repository link doesnt work!!

### ISSUE THREAD

**Issue by nazroid** [ranaaditya/SPYZIER-APP#1]
hi there
i like your projects 
https://github.com/ranaaditya/SPYZIER-APP
 but the link For the child or client app clone my repository doesnt work!!
pls solve the link problem and tell me back

**Comment by ranaaditya** [comment]
Hi nazroid , thanks for informing me about this issue. Child repository was
private but now i have made it public, you can access it !!

**Comment by ranaaditya** [comment]
@nazroid I am closing this issue as repository link is working.

**Comment by nazroid** [comment]
Thank you so much,nice job
