### ISSUE TITLE
parent app issues blank screen 

### ISSUE THREAD

**Issue by redeyehere** [ranaaditya/SPYZIER-APP#11]
i built both of the apps and the child app shows with a botton and the parent app is full blank screen 
please can u provide some screens how the apps looks and for the features as well

**Comment by ranaaditya** [comment]
> i built both of the apps and the child app shows with a botton and the parent app is full blank screen
> please can u provide some screens how the apps looks and for the features as well

can you provide screenshot ?

**Comment by adilirshad** [comment]
Same for me. Parent app issuing blank screen. On opening parent app. getting a notification 'successful' that's it. Then a black screen remains.
