### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by saniakhan7** [ranaaditya/SPYZIER-APP#15]
ap YouTube pe hain? Aur is project k youtube pe tutorials hain? Mujhy ye app bnani agar ap apnay YT ka link ya name bta dyn.

**Comment by ranaaditya** [comment]
Hi @saniakhan7 , no neither me nor tutorials of this app are on youtube.
Code is simple if you have any prior knowledge of android application development, if not I will suggest you to make some small apps before trying this.

Thanks !

**Comment by saniakhan7** [comment]
Hello! How are you? The code of sypzier app not working for me. Can you
help me? Please.
