### ISSUE TITLE
NO CHILD APP

### ISSUE THREAD

**Issue by folajin** [ranaaditya/SPYZIER-APP#6]
https://github.com/ranaaditya/Child, this link is dead. Please update. NO CHILD APP

**Comment by ranaaditya** [comment]
> https://github.com/ranaaditya/Child, this link is dead. Please update. NO CHILD APP

Hi @folajin I will soon make the Child app public.

**Comment by ranaaditya** [comment]
> https://github.com/ranaaditya/Child, this link is dead. Please update. NO CHILD APP

hey hi @folajin  made the requested link public !

now child-app is submodule inside this repository, no need to go anywhere else !

and please do give a star if you like this project !

happy coding :)
