### ISSUE TITLE
Child App

### ISSUE THREAD

**Issue by yashinfotech1018** [ranaaditya/SPYZIER-APP#7]
Sir Child App Not Found

**Comment by yashinfotech1018** [comment]
Will you provide the child app I want to buy. contact me on

my skype id - androidapps080@gmail.com

**Comment by ranaaditya** [comment]
> Will you provide the child app I want to buy. contact me on
> 
> my skype id - [androidapps080@gmail.com](mailto:androidapps080@gmail.com)

hey hi @yashinfotech1018  made the requested link public !

now child-app is submodule inside this repository, no need to go anywhere else !

and please do give a star if you like this project !

happy coding :)
